### ISSUE TITLE
Checkbox group problem

### ISSUE THREAD

**Issue by dolegr1** [livewire/flux#1094]
### Flux version

v1.1.3

### Livewire version

v3.5.18

### Tailwind version

v4.0.0

### What is the problem?

Hi, i have a problem with the component checkbox group. 
I have a table with a checkbox and input. If I change the value in the input field (email in table-row component) then selected (checkbox group wire:model) has the value of the email field.
The email field is for simplicity, normally there is an edit form there.

### Code snippets

    //table component
    <flux:checkbox.group wire:model.live="selected">
        <flux:table>
            <flux:columns>
                <flux:column class="w-5 !pl-3">
                    <flux:checkbox.all />
                </flux:column>
                <flux:column class="w-2/3">
                    <x-admin.table.sortable column="name" :$sortCol :$sortAsc>Nazwa</x-admin.table.sortable>
                </flux:column>
                <flux:column>
                    <x-admin.table.sortable column="status" :$sortCol :$sortAsc>Status</x-admin.table.sortable>
                </flux:column>
                <flux:column></flux:column>
            </flux:columns>
    
            <flux:rows>
                @foreach ($catalogs as $catalog)
                    <livewire:admin.setting.catalog.table-row
                        :key="$catalog->id"
                        :$catalog
                        @deleted="delete({{ $catalog->id }})"
                        @refreshed="$refresh"
                    />
                @endforeach
            </flux:rows>
        </flux:table>
    </flux:checkbox.group>

    //table-row componet
    <flux:row>
        <flux:cell class="!pl-3">
            <flux:checkbox wire:key="selectedCheckbox-{{ $catalog->id }}" value="{{ $catalog->id }}" />
        </flux:cell>
        <flux:cell>
            {{ $catalog->name }}
        </flux:cell>
        <flux:cell>
            <flux:badge
                color="{{ $catalog->status->color() }}"
                icon-trailing="{{ $catalog->status->icon() }}"
                variant="pill"
                inset="top bottom"
            >
                {{ $catalog->status->label() }}
            </flux:badge>
        </flux:cell>
        <flux:cell>
            <div class="flex gap-2 pr-3">
                <flux:spacer />
                <flux:input wire:model="email" type="email" />
            </div>
        </flux:cell>
    </flux:row>

### How do you expect it to work?

Wire model checkbox group should not take values ​​of other fields in this component.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@dolegr1 Your snippet has quite a few external property dependencies and custom components so no one can simply copy/paste it to reproduce your issue to try to help.

Please provide a snippet that can be easily copy/pasted to reproduce the issue(Volt components are great for this).

PS Flux doesn't support Tailwind CSS yet.  (2 days to Flux 2.0!)

**Comment by dolegr1** [comment]
Thanks for your reply,
I'll wait for Flux 2.0 and let you know if the problem still exists.

**Comment by joshhanley** [comment]
@dolegr1 thanks for reporting! The issue is that you have an input inside the checkbox group, so any input events from the input are bubbling up to the checkbox group which is being listened to by the `wire:model.live="selected` on it.

I think we should fix this, but as a work around for now, try changing it to `wire:model.self.live`, like

```blade
<flux:checkbox.group wire:model.self.live="selected">
```

**Comment by dolegr1** [comment]
Thanks for your help it works.
I have a question, because I'm just learning livewire, where do you know 'wire:model.self' from because I didn't find anything like that in the documentation.

**Comment by joshhanley** [comment]
@dolegr1 heh I know it because I've been working on Livewire for 4 years 😅 I just looked and couldn't find anything in the docs either. Probably just an oversight

**Comment by dolegr1** [comment]
I've been learning livewire for 2 months, so I still have a lot to learn.
Thanks again for your help

**Comment by joshhanley** [comment]
@dolegr1 no worries! I've reopened it as we can handle this better in Flux 🙂

**Comment by joshhanley** [comment]
@dolegr1 the checkbox group basically shouldn't ever actually listen to input events for elements inside of it, so we can default it to `.self` under the hood

**Comment by joshhanley** [comment]
I've submitted a PR with a fix

**Comment by joshhanley** [comment]
This has been released in v2.0
