### ISSUE TITLE
Dark Mode Flash

### ISSUE THREAD

**Issue by mute92** [livewire/flux#1501]
### Flux version

2.1.4

### Livewire version

3.6.3

### Tailwind version

4.1.4

### Browser and Operating System

Chrome

### What is the problem?

The page is flashing in dark mode. I am using Laravel 12 without starter kits.

https://github.com/user-attachments/assets/33494063-7295-4bf2-9810-d094a18557e3

### Code snippets

layout
```blade<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>{{ $title ?? 'Page Title' }}</title>

         <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

  @vite(['resources/css/app.css', 'resources/js/app.js'])

     @fluxAppearance
      @livewireStyles
</head>
<body class="min-h-screen bg-white dark:bg-zinc-800">
    <flux:sidebar sticky stashable class="bg-zinc-50 dark:bg-zinc-900 border-r rtl:border-r-0 rtl:border-l border-zinc-200 dark:border-zinc-700">
        <flux:sidebar.toggle class="lg:hidden" icon="x-mark" />
        <flux:brand href="#" logo="https://fluxui.dev/img/demo/logo.png" name="Acme Inc." class="px-2 dark:hidden" />
        <flux:brand href="#" logo="https://fluxui.dev/img/demo/dark-mode-logo.png" name="Acme Inc." class="px-2 hidden dark:flex" />
        <flux:input as="button" variant="filled" placeholder="Search..." icon="magnifying-glass" />
        <flux:navlist variant="outline">
            <flux:navlist.item icon="home" :href="route('dashboard')" :current="request()->routeIs('dashboard')">Dashboard</flux:navlist.item>
            <flux:navlist.item icon="user" badge="12" href="{{route('drivers')}}" :current="request()->routeIs('drivers')">Drivers</flux:navlist.item>
            <flux:navlist.item icon="document-text"  href="{{route('orders')}}">Orders</flux:navlist.item>
           
        </flux:navlist>
        <flux:spacer />
        <flux:navlist variant="outline">
            <flux:navlist.item icon="cog-6-tooth" href="#">Settings</flux:navlist.item>
            <flux:navlist.item icon="information-circle" href="#">Help</flux:navlist.item>
        </flux:navlist>
        <flux:dropdown position="top" align="start" class="max-lg:hidden">
              <flux:profile name="{{ Auth::user()->name }}" />
            <flux:menu>
               <flux:radio.group x-data variant="segmented" x-model="$flux.appearance">
                <flux:radio value="light" icon="sun" />
                <flux:radio value="dark" icon="moon" />
                </flux:radio.group>
                <flux:menu.item  href="#">Integrations</flux:menu.item>
                <flux:menu.item  href="#">Support</flux:menu.item>
                  <flux:menu.separator />

                
              <form method="POST" action="{{ route('logout') }}" id="logout-form">
    @csrf
    <flux:menu.item
        icon="arrow-right-start-on-rectangle"
        onclick="document.getElementById('logout-form').submit();"
    >
        Logout
    </flux:menu.item>
            </flux:menu>
        </flux:dropdown>
    </flux:sidebar>
    <flux:header class="lg:hidden">
        <flux:sidebar.toggle class="lg:hidden" icon="bars-2" inset="left" />
        <flux:spacer />
        <flux:dropdown position="top" alignt="start">
            <flux:profile name="{{ Auth::user()->name }}" />
            <flux:menu>
              
                <flux:menu.separator />
                <form method="POST" action="{{ route('logout') }}" id="logout-form">
    @csrf
    <flux:menu.item
        icon="arrow-right-start-on-rectangle"
        onclick="document.getElementById('logout-form').submit();"
    >
        Logout
    </flux:menu.item>
            </flux:menu>
        </flux:dropdown>
    </flux:header>
    <flux:main>
  {{ $slot }}
    </flux:main>
    @fluxScripts

        @livewireScripts

    @persist('toast')
        <flux:toast />
    @endpersist
</body>
</html>
```
app.css
```blade
@import 'tailwindcss';
@import '../../vendor/livewire/flux/dist/flux.css';
@custom-variant dark (&:where(.dark, .dark *));

/* Re-assign Flux's gray of choice... */
@theme {
    --color-zinc-50: var(--color-slate-50);
    --color-zinc-100: var(--color-slate-100);
    --color-zinc-200: var(--color-slate-200);
    --color-zinc-300: var(--color-slate-300);
    --color-zinc-400: var(--color-slate-400);
    --color-zinc-500: var(--color-slate-500);
    --color-zinc-600: var(--color-slate-600);
    --color-zinc-700: var(--color-slate-700);
    --color-zinc-800: var(--color-slate-800);
    --color-zinc-900: var(--color-slate-900);
    --color-zinc-950: var(--color-slate-950);
}

@theme {
    --color-accent: var(--color-violet-500);
    --color-accent-content: var(--color-violet-600);
    --color-accent-foreground: var(--color-white);
}

@layer theme {
    .dark {
        --color-accent: var(--color-violet-500);
        --color-accent-content: var(--color-violet-400);
        --color-accent-foreground: var(--color-white);
    }
}


```
```blade
<?php

namespace App\Livewire\Dashboard;

use Livewire\Component;

class Dashboard extends Component
{
    public function render()
    {
        return view('livewire..dashboard.dashboard');
    }
}

```

```blade
<div>
     <flux:heading size="xl" level="1">Dashboard</flux:heading>
     <flux:separator variant="subtle" class="mb-4 mt-2"/>
</div>

```

```blade
<?php

namespace App\Livewire\Orders;

use Livewire\Component;

class Orders extends Component
{
    public function render()
    {
        return view('livewire.orders.orders');
    }
}

```

```blade
<div>
           <flux:heading size="xl" level="1">Orders</flux:heading>
        <flux:separator variant="subtle" class="mb-4 mt-2"/>
</div>

```

Vite
```blade
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
        tailwindcss(),
    ],
});

```

### How do you expect it to work?

Without flashing. 

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@mute92 Can you share your `tailwind.config.js` and your `app.js` files?

**Comment by mute92** [comment]
There is no tailwind.config.js in version 4.

app.js
```blade
import './bootstrap';`
```

boostrap.js
```blade
import axios from 'axios';
window.axios = axios;

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
```

**Comment by jeffchown** [comment]
(some people have a leftover `tailwind.config.js` from somewhere, so wanted to make sure)

As you are not loading Livewire manually in your `app.js`, have you tried?:
- removing the`@livewireStyles` and `@livewireScripts` lines
- `@fluxScripts` to just before the `</body>`?
- then running `php artisan view:clear` and `npm run build` and try again

**Comment by mute92** [comment]
@jeffchown I tried your recommendation and also commented out bootstrap from app.js, but I still have the same issue. I do have this in my console, so I don't know if it's related. 

![Image](https://github.com/user-attachments/assets/98fd7e6c-7c0c-415f-a2d1-7348015811f6)

**Comment by jeffchown** [comment]
@mute92 The console errors definitely suggest a js issue.

The `import './bootstrap';` is important - you can't comment that out without creating issues/errors.
With the `bootstrap` line *uncommented* do you still get the console errors?

**Comment by jeffchown** [comment]
@mute92 Can you open the Network tab in the dev tools, refresh your page, then scan the network tab's list of files loaded for any that are in red?

**Comment by jeffchown** [comment]
Glad you got it fixed @mute92 👍

**Comment by mute92** [comment]
@jeffchown I am sorry for the confisution, before when I had an issue with js,CSS not loading I fixed with that line in nginx, but the blinking issue its still ongoing. :(

**Comment by mute92** [comment]
This is the Mozilla console

![Image](https://github.com/user-attachments/assets/551ea1c5-bb5f-4b74-b345-a4eae38ade97)

**Comment by jeffchown** [comment]
Gotcha @mute92.  Sounds like your local dev setup is different than mine (I use Herd/Valet).

As an experiment, can you try adding this:
```
<script>
    window.localStorage.setItem('flux.appearance', 'dark');
</script>
```
just before `@fluxAppearance`?

This is not a fix (as it will force your app into dark mode all the time) but it might give us a clue.

**Comment by jeffchown** [comment]
@mute92 Just had a closer look at your layout.blade - I can find a closing `</form>` tag for both your Logout forms.  That might be causing the issue.

**Comment by mute92** [comment]
@jeffchown 
I did removed the form completly, but still same issue, tried with that script above as well same issue.

**Comment by jeffchown** [comment]
And you're running `php artisan view:clear` and `npm run build` after each change?

When you view you page's source code in dev tools, do you see:

```
<style>
    :root.dark {
        color-scheme: dark;
    }
</style>
<script>
    window.Flux = {
        applyAppearance (appearance) {
            let applyDark = () => document.documentElement.classList.add('dark')
            let applyLight = () => document.documentElement.classList.remove('dark')

            if (appearance === 'system') {
                let media = window.matchMedia('(prefers-color-scheme: dark)')

                window.localStorage.removeItem('flux.appearance')

                media.matches ? applyDark() : applyLight()
            } else if (appearance === 'dark') {
                window.localStorage.setItem('flux.appearance', 'dark')

                applyDark()
            } else if (appearance === 'light') {
                window.localStorage.setItem('flux.appearance', 'light')

                applyLight()
            }
        }
    }

    window.Flux.applyAppearance(window.localStorage.getItem('flux.appearance') || 'system')
</script>
```

just before `</head>`?

**Comment by mute92** [comment]
@jeffchown 

```blade

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Page Title</title>

         <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

  <link rel="preload" as="style" href="https://domain.com/build/assets/app-BMjLn5ob.css" /><link rel="modulepreload" href="https://domain.com/build/assets/app-eMHK6VFw.js" /><link rel="stylesheet" href="https://domain.com/build/assets/app-BMjLn5ob.css" data-navigate-track="reload" /><script type="76e17fc173ae624345b58438-module" src="https://domain.com/build/assets/app-eMHK6VFw.js" data-navigate-track="reload"></script>
     <style>
    :root.dark {
        color-scheme: dark;
    }
</style>
<script type="76e17fc173ae624345b58438-text/javascript">
    window.Flux = {
        applyAppearance (appearance) {
            let applyDark = () => document.documentElement.classList.add('dark')
            let applyLight = () => document.documentElement.classList.remove('dark')

            if (appearance === 'system') {
                let media = window.matchMedia('(prefers-color-scheme: dark)')

                window.localStorage.removeItem('flux.appearance')

                media.matches ? applyDark() : applyLight()
            } else if (appearance === 'dark') {
                window.localStorage.setItem('flux.appearance', 'dark')

                applyDark()
            } else if (appearance === 'light') {
                window.localStorage.setItem('flux.appearance', 'light')

                applyLight()
            }
        }
    }

    window.Flux.applyAppearance(window.localStorage.getItem('flux.appearance') || 'system')
</script>
<!-- Livewire Styles --><style >[wire\:loading][wire\:loading], [wire\:loading\.delay][wire\:loading\.delay], [wire\:loading\.inline-block][wire\:loading\.inline-block], [wire\:loading\.inline][wire\:loading\.inline], [wire\:loading\.block][wire\:loading\.block], [wire\:loading\.flex][wire\:loading\.flex], [wire\:loading\.table][wire\:loading\.table], [wire\:loading\.grid][wire\:loading\.grid], [wire\:loading\.inline-flex][wire\:loading\.inline-flex] {display: none;}[wire\:loading\.delay\.none][wire\:loading\.delay\.none], [wire\:loading\.delay\.shortest][wire\:loading\.delay\.shortest], [wire\:loading\.delay\.shorter][wire\:loading\.delay\.shorter], [wire\:loading\.delay\.short][wire\:loading\.delay\.short], [wire\:loading\.delay\.default][wire\:loading\.delay\.default], [wire\:loading\.delay\.long][wire\:loading\.delay\.long], [wire\:loading\.delay\.longer][wire\:loading\.delay\.longer], [wire\:loading\.delay\.longest][wire\:loading\.delay\.longest] {display: none;}[wire\:offline][wire\:offline] {display: none;}[wire\:dirty]:not(textarea):not(input):not(select) {display: none;}:root {--livewire-progress-bar-color: #2299dd;}[x-cloak] {display: none !important;}[wire\:cloak] {display: none !important;}</style>
</head>
<body class="min-h-screen bg-slate-100 dark:bg-zinc-800">
    <div
    class="z-10 fixed inset-0 bg-black/10 hidden [[data-show-stashed-sidebar]_&]:block lg:[[data-show-stashed-sidebar]_&]:hidden"
    x-data x-on:click="document.body.removeAttribute('data-show-stashed-sidebar')"
></div>

<div class="[grid-area:sidebar] z-1 flex flex-col gap-4 [:where(&amp;)]:w-64 p-4 max-lg:data-mobile-cloak:hidden [[data-show-stashed-sidebar]_&amp;]:translate-x-0! lg:translate-x-0! z-20! data-stashed:start-0! data-stashed:fixed! data-stashed:top-0! data-stashed:min-h-dvh! data-stashed:max-h-dvh! max-h-dvh overflow-y-auto overscroll-contain bg-zinc-50 dark:bg-zinc-900 border-r rtl:border-r-0 rtl:border-l border-zinc-200 dark:border-zinc-700" x-bind:data-stashed="! screenLg" x-resize.document="screenLg = window.innerWidth &gt;= 1024" x-init="$el.classList.add(&#039;-translate-x-full&#039;, &#039;rtl:translate-x-full&#039;); $el.removeAttribute(&#039;data-mobile-cloak&#039;); $el.classList.add(&#039;transition-transform&#039;)" x-bind:style="{ position: &#039;sticky&#039;, top: $el.offsetTop + &#039;px&#039;, &#039;max-height&#039;: &#039;calc(100dvh - &#039; + $el.offsetTop + &#039;px)&#039; }" x-data="{ screenLg: window.innerWidth >= 1024 }" data-mobile-cloak data-flux-sidebar>
    <button type="button" class="relative items-center font-medium justify-center gap-2 whitespace-nowrap disabled:opacity-75 dark:disabled:opacity-75 disabled:cursor-default disabled:pointer-events-none h-10 text-sm rounded-lg w-10 inline-flex  bg-transparent hover:bg-zinc-800/5 dark:hover:bg-white/15 text-zinc-400 hover:text-zinc-800 dark:text-zinc-400 dark:hover:text-white     shrink-0 lg:hidden" data-flux-button="data-flux-button" x-data="" x-on:click="document.body.hasAttribute('data-show-stashed-sidebar') ? document.body.removeAttribute('data-show-stashed-sidebar') : document.body.setAttribute('data-show-stashed-sidebar', '')" data-flux-sidebar-toggle="data-flux-sidebar-toggle" aria-label="Toggle sidebar">
        <svg class="shrink-0 [:where(&amp;)]:size-5" data-flux-icon xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
  <path d="M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z"/>
</svg>
    </button>
        <a href="#" class="h-10 flex items-center me-4 gap-2 px-2 dark:hidden" data-flux-brand>
                    <div class="flex items-center justify-center h-6 rounded-sm overflow-hidden shrink-0">
                                    <img src="https://fluxui.dev/img/demo/logo.png" alt="" class="h-6" />
                            </div>
        
        <div class="text-sm font-medium truncate [:where(&amp;)]:text-zinc-800 dark:[:where(&amp;)]:text-zinc-100">Acme Inc.</div>
    </a>
        <a href="#" class="h-10 flex items-center me-4 gap-2 px-2 hidden dark:flex" data-flux-brand>
                    <div class="flex items-center justify-center h-6 rounded-sm overflow-hidden shrink-0">
                                    <img src="https://fluxui.dev/img/demo/dark-mode-logo.png" alt="" class="h-6" />
                            </div>
        
        <div class="text-sm font-medium truncate [:where(&amp;)]:text-zinc-800 dark:[:where(&amp;)]:text-zinc-100">Acme Inc.</div>
    </a>
        <button class="w-full border rounded-lg block disabled:shadow-none dark:shadow-none appearance-none text-base sm:text-sm py-2 h-10 leading-[1.375rem] ps-10 pe-3 bg-zinc-800/5 dark:bg-white/10 dark:disabled:bg-white/[7%] text-zinc-700 placeholder-zinc-500 disabled:placeholder-zinc-400 dark:text-zinc-200 dark:placeholder-white/60 dark:disabled:placeholder-white/40 border-0  w-full relative flex" type="button" placeholder="Search...">
                    <div class="absolute top-0 bottom-0 flex items-center justify-center text-xs text-zinc-400/75 ps-3 start-0">
                <svg class="shrink-0 [:where(&amp;)]:size-5" data-flux-icon xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
  <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 1 0 0 11 5.5 5.5 0 0 0 0-11ZM2 9a7 7 0 1 1 12.452 4.391l3.328 3.329a.75.75 0 1 1-1.06 1.06l-3.329-3.328A7 7 0 0 1 2 9Z" clip-rule="evenodd"/>
</svg>

                    </div>
        
                    <div class="block self-center text-start flex-1 font-medium text-zinc-400 dark:text-white/40">
                Search...
            </div>
        
        
            </button>
        <nav class="flex flex-col overflow-visible min-h-auto" data-flux-navlist>
    <a href="https://domain.com" class="h-10 lg:h-8 relative flex items-center gap-3 rounded-lg  py-0 text-start w-full px-3 my-px text-zinc-500 dark:text-white/80 data-current:text-(--color-accent-content) hover:data-current:text-(--color-accent-content) data-current:bg-white dark:data-current:bg-white/[7%] data-current:border data-current:border-zinc-200 dark:data-current:border-transparent hover:text-zinc-800 dark:hover:text-white dark:hover:bg-white/[7%] hover:bg-zinc-800/5  border border-transparent" data-flux-navlist-item="data-flux-navlist-item">
        <div class="relative">
                            <svg class="shrink-0 [:where(&amp;)]:size-6 size-4!" data-flux-icon xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
  <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25"/>
</svg>

                    
                    </div>
    
            <div class="flex-1 text-sm font-medium leading-none whitespace-nowrap [[data-nav-footer]_&]:hidden [[data-nav-sidebar]_[data-nav-footer]_&]:block" data-content>Dashboard</div>
    </a>
            <a href="https://domain.com/drivers" class="h-10 lg:h-8 relative flex items-center gap-3 rounded-lg  py-0 text-start w-full px-3 my-px text-zinc-500 dark:text-white/80 data-current:text-(--color-accent-content) hover:data-current:text-(--color-accent-content) data-current:bg-white dark:data-current:bg-white/[7%] data-current:border data-current:border-zinc-200 dark:data-current:border-transparent hover:text-zinc-800 dark:hover:text-white dark:hover:bg-white/[7%] hover:bg-zinc-800/5  border border-transparent" data-flux-navlist-item="data-flux-navlist-item">
        <div class="relative">
                            <svg class="shrink-0 [:where(&amp;)]:size-6 size-4!" data-flux-icon xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
  <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z"/>
</svg>

                    
                    </div>
    
            <div class="flex-1 text-sm font-medium leading-none whitespace-nowrap [[data-nav-footer]_&]:hidden [[data-nav-sidebar]_[data-nav-footer]_&]:block" data-content>Drivers</div>
    
    
            <span class="text-xs font-medium rounded-sm px-1 py-0.5 text-zinc-700 dark:text-zinc-200 bg-zinc-400/15 dark:bg-white/10">12</span>
    </a>
            <a href="https://domain.com/orders" class="h-10 lg:h-8 relative flex items-center gap-3 rounded-lg  py-0 text-start w-full px-3 my-px text-zinc-500 dark:text-white/80 data-current:text-(--color-accent-content) hover:data-current:text-(--color-accent-content) data-current:bg-white dark:data-current:bg-white/[7%] data-current:border data-current:border-zinc-200 dark:data-current:border-transparent hover:text-zinc-800 dark:hover:text-white dark:hover:bg-white/[7%] hover:bg-zinc-800/5  border border-transparent" data-flux-navlist-item="data-flux-navlist-item">
        <div class="relative">
                            <svg class="shrink-0 [:where(&amp;)]:size-6 size-4!" data-flux-icon xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z"/>
</svg>

                    
                    </div>
    
            <div class="flex-1 text-sm font-medium leading-none whitespace-nowrap [[data-nav-footer]_&]:hidden [[data-nav-sidebar]_[data-nav-footer]_&]:block" data-content>Orders</div>
    </a>
</nav>
        <div class="flex-1" data-flux-spacer></div>
        <nav class="flex flex-col overflow-visible min-h-auto" data-flux-navlist>
    <a href="#" class="h-10 lg:h-8 relative flex items-center gap-3 rounded-lg  py-0 text-start w-full px-3 my-px text-zinc-500 dark:text-white/80 data-current:text-(--color-accent-content) hover:data-current:text-(--color-accent-content) data-current:bg-white dark:data-current:bg-white/[7%] data-current:border data-current:border-zinc-200 dark:data-current:border-transparent hover:text-zinc-800 dark:hover:text-white dark:hover:bg-white/[7%] hover:bg-zinc-800/5  border border-transparent" data-flux-navlist-item="data-flux-navlist-item">
        <div class="relative">
                            <svg class="shrink-0 [:where(&amp;)]:size-6 size-4!" data-flux-icon xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
  <path stroke-linecap="round" stroke-linejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.94-1.11.94h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28Z"/>
  <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
</svg>

                    
                    </div>
    
            <div class="flex-1 text-sm font-medium leading-none whitespace-nowrap [[data-nav-footer]_&]:hidden [[data-nav-sidebar]_[data-nav-footer]_&]:block" data-content>Settings</div>
    </a>
            <a href="#" class="h-10 lg:h-8 relative flex items-center gap-3 rounded-lg  py-0 text-start w-full px-3 my-px text-zinc-500 dark:text-white/80 data-current:text-(--color-accent-content) hover:data-current:text-(--color-accent-content) data-current:bg-white dark:data-current:bg-white/[7%] data-current:border data-current:border-zinc-200 dark:data-current:border-transparent hover:text-zinc-800 dark:hover:text-white dark:hover:bg-white/[7%] hover:bg-zinc-800/5  border border-transparent" data-flux-navlist-item="data-flux-navlist-item">
        <div class="relative">
                            <svg class="shrink-0 [:where(&amp;)]:size-6 size-4!" data-flux-icon xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
  <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z"/>
</svg>

                    
                    </div>
    
            <div class="flex-1 text-sm font-medium leading-none whitespace-nowrap [[data-nav-footer]_&]:hidden [[data-nav-sidebar]_[data-nav-footer]_&]:block" data-content>Help</div>
    </a>
</nav>
        <ui-dropdown position="top start" class="max-lg:hidden" data-flux-dropdown>
    <button type="button" class="group flex items-center rounded-lg has-data-[circle=true]:rounded-full [ui-dropdown&gt;&amp;]:w-full p-1 hover:bg-zinc-800/5 dark:hover:bg-white/10" data-flux-profile>
    <div class="shrink-0">
                    <div data-flux-avatar="data-flux-avatar" data-slot="avatar" data-size="sm" class="[:where(&amp;)]:size-8 [:where(&amp;)]:text-sm [--avatar-radius:var(--radius-md)] relative isolate flex items-center justify-center [:where(&amp;)]:font-medium rounded-[var(--avatar-radius)] [:where(&amp;)]:bg-zinc-200 [:where(&amp;)]:dark:bg-zinc-600 [:where(&amp;)]:text-zinc-800 [:where(&amp;)]:dark:text-white  after:absolute after:inset-0 after:inset-ring-[1px] after:inset-ring-black/7 dark:after:inset-ring-white/10 after:rounded-md">
        <span class="select-none">AM</span>
    </div>
            </div>

            <span class="mx-2 text-sm text-zinc-500 dark:text-white/80 group-hover:text-zinc-800 dark:group-hover:text-white font-medium truncate">
            name
        </span>
    
            <div class="shrink-0 ms-auto size-8 flex justify-center items-center">
            <svg class="shrink-0 [:where(&amp;)]:size-4 text-zinc-400 dark:text-white/80 group-hover:text-zinc-800 dark:group-hover:text-white" data-flux-icon xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" data-slot="icon">
  <path fill-rule="evenodd" d="M4.22 6.22a.75.75 0 0 1 1.06 0L8 8.94l2.72-2.72a.75.75 0 1 1 1.06 1.06l-3.25 3.25a.75.75 0 0 1-1.06 0L4.22 7.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd"/>
</svg>

                </div>
    </button>
            <ui-menu
    class="[:where(&amp;)]:min-w-48 p-[.3125rem] rounded-lg shadow-xs border border-zinc-200 dark:border-zinc-600 bg-white dark:bg-zinc-700 focus:outline-hidden"
    popover="manual"
    data-flux-menu
>
    <ui-radio-group class="block flex p-1 rounded-lg bg-zinc-800/5 dark:bg-white/10 h-10 p-1" x-data="" x-model="$flux.appearance"  data-flux-radio-group-segmented>
        <ui-radio class="flex whitespace-nowrap flex-1 justify-center items-center gap-2 rounded-md data-checked:shadow-xs text-sm font-medium text-zinc-600 hover:text-zinc-800 dark:hover:text-white dark:text-white/70 data-checked:text-zinc-800 dark:data-checked:text-white data-checked:bg-white dark:data-checked:bg-white/20 [&amp;[disabled]]:opacity-50 dark:[&amp;[disabled]]:opacity-75 [&amp;[disabled]]:cursor-default [&amp;[disabled]]:pointer-events-none px-4" value="light" data-flux-control data-flux-radio-segmented tabindex="-1">
            <svg class="shrink-0 [:where(&amp;)]:size-5 text-zinc-500 dark:text-zinc-400 [ui-radio[data-checked]_&]:text-zinc-800 dark:[ui-radio[data-checked]_&]:text-white" data-flux-icon xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
  <path d="M10 2a.75.75 0 0 1 .75.75v1.5a.75.75 0 0 1-1.5 0v-1.5A.75.75 0 0 1 10 2ZM10 15a.75.75 0 0 1 .75.75v1.5a.75.75 0 0 1-1.5 0v-1.5A.75.75 0 0 1 10 15ZM10 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6ZM15.657 5.404a.75.75 0 1 0-1.06-1.06l-1.061 1.06a.75.75 0 0 0 1.06 1.06l1.06-1.06ZM6.464 14.596a.75.75 0 1 0-1.06-1.06l-1.06 1.06a.75.75 0 0 0 1.06 1.06l1.06-1.06ZM18 10a.75.75 0 0 1-.75.75h-1.5a.75.75 0 0 1 0-1.5h1.5A.75.75 0 0 1 18 10ZM5 10a.75.75 0 0 1-.75.75h-1.5a.75.75 0 0 1 0-1.5h1.5A.75.75 0 0 1 5 10ZM14.596 15.657a.75.75 0 0 0 1.06-1.06l-1.06-1.061a.75.75 0 1 0-1.06 1.06l1.06 1.06ZM5.404 6.464a.75.75 0 0 0 1.06-1.06l-1.06-1.06a.75.75 0 1 0-1.061 1.06l1.06 1.06Z"/>
</svg>

            
    

    </ui-radio>
                <ui-radio class="flex whitespace-nowrap flex-1 justify-center items-center gap-2 rounded-md data-checked:shadow-xs text-sm font-medium text-zinc-600 hover:text-zinc-800 dark:hover:text-white dark:text-white/70 data-checked:text-zinc-800 dark:data-checked:text-white data-checked:bg-white dark:data-checked:bg-white/20 [&amp;[disabled]]:opacity-50 dark:[&amp;[disabled]]:opacity-75 [&amp;[disabled]]:cursor-default [&amp;[disabled]]:pointer-events-none px-4" value="dark" data-flux-control data-flux-radio-segmented tabindex="-1">
            <svg class="shrink-0 [:where(&amp;)]:size-5 text-zinc-500 dark:text-zinc-400 [ui-radio[data-checked]_&]:text-zinc-800 dark:[ui-radio[data-checked]_&]:text-white" data-flux-icon xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
  <path fill-rule="evenodd" d="M7.455 2.004a.75.75 0 0 1 .26.77 7 7 0 0 0 9.958 7.967.75.75 0 0 1 1.067.853A8.5 8.5 0 1 1 6.647 1.921a.75.75 0 0 1 .808.083Z" clip-rule="evenodd"/>
</svg>

            
    

    </ui-radio>
    </ui-radio-group>
                <a href="#" class="flex items-center px-2 py-1.5 w-full focus:outline-hidden rounded-md text-start text-sm font-medium [&amp;[disabled]]:opacity-50 text-zinc-800 data-active:bg-zinc-50 dark:text-white dark:data-active:bg-zinc-600 **:data-flux-menu-item-icon:text-zinc-400 dark:**:data-flux-menu-item-icon:text-white/60 [&amp;[data-active]_[data-flux-menu-item-icon]]:text-current" data-flux-menu-item="data-flux-menu-item">
        <div class="w-7 hidden [[data-flux-menu]:has(>[data-flux-menu-item-has-icon])_&]:block"></div>
    
    Integrations
    </a>
                <a href="#" class="flex items-center px-2 py-1.5 w-full focus:outline-hidden rounded-md text-start text-sm font-medium [&amp;[disabled]]:opacity-50 text-zinc-800 data-active:bg-zinc-50 dark:text-white dark:data-active:bg-zinc-600 **:data-flux-menu-item-icon:text-zinc-400 dark:**:data-flux-menu-item-icon:text-white/60 [&amp;[data-active]_[data-flux-menu-item-icon]]:text-current" data-flux-menu-item="data-flux-menu-item">
        <div class="w-7 hidden [[data-flux-menu]:has(>[data-flux-menu-item-has-icon])_&]:block"></div>
    
    Support
    </a>
                  <div class="-mx-[.3125rem] my-[.3125rem] h-px"  data-flux-menu-separator>
    <div data-orientation="horizontal" role="none" class="border-0 [print-color-adjust:exact] bg-zinc-800/15 dark:bg-white/20 h-px w-full dark:bg-zinc-600!" data-flux-separator></div>
</div>
</ui-menu>
</ui-dropdown>
</div>
    <header class="[grid-area:header] z-10 min-h-14 flex items-center px-6 lg:px-8 lg:hidden" data-flux-header>
            <button type="button" class="relative items-center font-medium justify-center gap-2 whitespace-nowrap disabled:opacity-75 dark:disabled:opacity-75 disabled:cursor-default disabled:pointer-events-none h-10 text-sm rounded-lg w-10 inline-flex -ms-2.5 bg-transparent hover:bg-zinc-800/5 dark:hover:bg-white/15 text-zinc-400 hover:text-zinc-800 dark:text-zinc-400 dark:hover:text-white     shrink-0 lg:hidden" data-flux-button="data-flux-button" x-data="" x-on:click="document.body.hasAttribute('data-show-stashed-sidebar') ? document.body.removeAttribute('data-show-stashed-sidebar') : document.body.setAttribute('data-show-stashed-sidebar', '')" data-flux-sidebar-toggle="data-flux-sidebar-toggle" aria-label="Toggle sidebar">
        <svg class="shrink-0 [:where(&amp;)]:size-5" data-flux-icon xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
  <path fill-rule="evenodd" d="M2 6.75A.75.75 0 0 1 2.75 6h14.5a.75.75 0 0 1 0 1.5H2.75A.75.75 0 0 1 2 6.75Zm0 6.5a.75.75 0 0 1 .75-.75h14.5a.75.75 0 0 1 0 1.5H2.75a.75.75 0 0 1-.75-.75Z" clip-rule="evenodd"/>
</svg>
    </button>
        <div class="flex-1" data-flux-spacer></div>
        <ui-dropdown position="top start" alignt="start" data-flux-dropdown>
    <button type="button" class="group flex items-center rounded-lg has-data-[circle=true]:rounded-full [ui-dropdown&gt;&amp;]:w-full p-1 hover:bg-zinc-800/5 dark:hover:bg-white/10" data-flux-profile>
    <div class="shrink-0">
                    <div data-flux-avatar="data-flux-avatar" data-slot="avatar" data-size="sm" class="[:where(&amp;)]:size-8 [:where(&amp;)]:text-sm [--avatar-radius:var(--radius-md)] relative isolate flex items-center justify-center [:where(&amp;)]:font-medium rounded-[var(--avatar-radius)] [:where(&amp;)]:bg-zinc-200 [:where(&amp;)]:dark:bg-zinc-600 [:where(&amp;)]:text-zinc-800 [:where(&amp;)]:dark:text-white  after:absolute after:inset-0 after:inset-ring-[1px] after:inset-ring-black/7 dark:after:inset-ring-white/10 after:rounded-md">
        <span class="select-none">AM</span>
    </div>
            </div>

            <span class="mx-2 text-sm text-zinc-500 dark:text-white/80 group-hover:text-zinc-800 dark:group-hover:text-white font-medium truncate">
            name
        </span>
    
            <div class="shrink-0 ms-auto size-8 flex justify-center items-center">
            <svg class="shrink-0 [:where(&amp;)]:size-4 text-zinc-400 dark:text-white/80 group-hover:text-zinc-800 dark:group-hover:text-white" data-flux-icon xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" data-slot="icon">
  <path fill-rule="evenodd" d="M4.22 6.22a.75.75 0 0 1 1.06 0L8 8.94l2.72-2.72a.75.75 0 1 1 1.06 1.06l-3.25 3.25a.75.75 0 0 1-1.06 0L4.22 7.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd"/>
</svg>

                </div>
    </button>
            <ui-menu
    class="[:where(&amp;)]:min-w-48 p-[.3125rem] rounded-lg shadow-xs border border-zinc-200 dark:border-zinc-600 bg-white dark:bg-zinc-700 focus:outline-hidden"
    popover="manual"
    data-flux-menu
>
    <div class="-mx-[.3125rem] my-[.3125rem] h-px"  data-flux-menu-separator>
    <div data-orientation="horizontal" role="none" class="border-0 [print-color-adjust:exact] bg-zinc-800/15 dark:bg-white/20 h-px w-full dark:bg-zinc-600!" data-flux-separator></div>
</div>
</ui-menu>
</ui-dropdown>
    </header>
    <div class="[grid-area:main] p-6 lg:p-8 [[data-flux-container]_&amp;]:px-0" data-flux-main>
    <h1>This is inside the layout component!</h1>
</div>


    <div x-persist="toast">
        <ui-toast x-data x-on:toast-show.document="$el.showToast($event.detail)" wire:ignore>
    <template>
        <div popover="manual" class="m-0 p-6 bg-transparent [&amp;[data-position*=top]]:mb-auto [&amp;[data-position*=bottom]]:mt-auto [&amp;[data-position*=right]]:ml-auto rtl:[&amp;[data-position*=right]]:ml-0 rtl:[&amp;[data-position*=right]]:mr-auto [&amp;[data-position*=left]]:mr-auto rtl:[&amp;[data-position*=left]]:mr-0 rtl:[&amp;[data-position*=left]]:ml-auto" data-position="bottom right" data-variant="" data-flux-toast-dialog>
            <div class="max-w-sm p-2 rounded-xl shadow-lg bg-white border border-zinc-200 border-b-zinc-300/80 dark:bg-zinc-700 dark:border-zinc-600">
                <div class="flex items-start gap-4">
                    <div class="flex-1 py-1.5 ps-2.5 flex gap-2">
                        
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="hidden [[data-flux-toast-dialog][data-variant=success]_&]:block shrink-0 mt-0.5 size-4 text-lime-600 dark:text-lime-400">
                            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14Zm3.844-8.791a.75.75 0 0 0-1.188-.918l-3.7 4.79-1.649-1.833a.75.75 0 1 0-1.114 1.004l2.25 2.5a.75.75 0 0 0 1.15-.043l4.25-5.5Z" clip-rule="evenodd" />
                        </svg>

                        
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="hidden [[data-flux-toast-dialog][data-variant=warning]_&]:block shrink-0 mt-0.5 size-4 text-amber-500 dark:text-amber-400">
                            <path fill-rule="evenodd" d="M6.701 2.25c.577-1 2.02-1 2.598 0l5.196 9a1.5 1.5 0 0 1-1.299 2.25H2.804a1.5 1.5 0 0 1-1.3-2.25l5.197-9ZM8 4a.75.75 0 0 1 .75.75v3a.75.75 0 1 1-1.5 0v-3A.75.75 0 0 1 8 4Zm0 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" clip-rule="evenodd" />
                        </svg>

                        
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="hidden [[data-flux-toast-dialog][data-variant=danger]_&]:block shrink-0 mt-0.5 size-4 text-rose-500 dark:text-rose-400">
                            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14ZM8 4a.75.75 0 0 1 .75.75v3a.75.75 0 0 1-1.5 0v-3A.75.75 0 0 1 8 4Zm0 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" clip-rule="evenodd" />
                        </svg>

                        <div>
                            
                            <div class="font-medium text-sm text-zinc-800 dark:text-white [&:not(:empty)+div]:font-normal [&:not(:empty)+div]:text-zinc-500 [&:not(:empty)+div]:dark:text-zinc-300 [&:not(:empty)]:pb-2"><slot name="heading"></slot></div>

                            
                            <div class="font-medium text-sm text-zinc-800 dark:text-white"><slot name="text"></slot></div>
                        </div>
                    </div>

                    
                    <div class="flex items-center">
                        <button type="button" onclick="if (!window.__cfRLUnblockHandlers) return false; this.closest('ui-toast').hideToast()" class="inline-flex items-center font-medium justify-center gap-2 truncate disabled:opacity-50 dark:disabled:opacity-75 disabled:cursor-default h-8 text-sm rounded-md w-8 bg-transparent hover:bg-zinc-800/5 dark:hover:bg-white/15 text-zinc-400 hover:text-zinc-800 dark:text-zinc-400 dark:hover:text-white" as="button" data-cf-modified-76e17fc173ae624345b58438-="">
                            <div>
                                <svg class="[:where(&)]:size-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
                                    <path d="M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z"></path>
                                </svg>
                            </div>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </template>
</ui-toast>
    </div>
        <script src="/flux/flux.js?id=2d5ecc7b" data-navigate-once type="76e17fc173ae624345b58438-text/javascript"></script>
<!-- Livewire Scripts -->
<script src="/livewire/livewire.js?id=df3a17f2" data-csrf="0HbUBeqjNlpvzx9fZcrSlmh29tHu8UlwsW8DYIlW" data-update-uri="/livewire/update" data-navigate-once="true" type="76e17fc173ae624345b58438-text/javascript"></script>
<script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="76e17fc173ae624345b58438-|49" defer></script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" data-cf-beacon='{"rayId":"93155edc6f5c225e","version":"2025.3.0","r":1,"token":"b729f5cbbed343309a8980967d98f659","serverTiming":{"name":{"cfExtPri":true,"cfL4":true,"cfSpeedBrain":true,"cfCacheStatus":true}}}' crossorigin="anonymous"></script>
</body>
</html>
```

**Comment by jeffchown** [comment]
@mute92 Is this running in your local env or on production? (looks like production)

**Comment by mute92** [comment]
@jeffchown its production envirment and its been created and modified directly there, regarding Cloudflare, the development Mode is on.

**Comment by jeffchown** [comment]
@mute92 Normally what I'd do in a case like this is try the same code/repo in my local env to see if it works.  If it does, then I know the code is OK and the issue is related to the other environment.

As I can't easily recreate your production environment, it's difficult to help past this point.

That said, a fresh set of eyes (@joshhanley ?) may see something in your posts that I didn't.

**Comment by jeffchown** [comment]
@mute92 Anything's possible.  What is your production stack? (e.g. I use Laravel Forge + Envoyer + Digital Ocean for production apps)

**Comment by mute92** [comment]
@jeffchown  cloudpanel + Hetzner

**Comment by joshhanley** [comment]
@mute92 thanks for reporting! Can you confirm a couple of things for me, what operating system are you on (not the server, but your machine that you're running Chrome on)? Also have you been able to replicate this issue in a local environment? Thanks!

**Comment by mute92** [comment]
@joshhanley @jeffchown 
I am using Windows, and I just tested on the local environment, and it was working fine, the issue is with the app being hosted in CloudPanel.

**Comment by jeffchown** [comment]
@mute92 Thanks for the update.  At least we have confirmation now.  
I have no experience with CloudPanel, so I'll have to leave this one to the CP experts in the community.

**Comment by joshhanley** [comment]
@mute92 thanks for confirming. I'm using one of the Laravel starter kits deployed to Laravel Cloud and it doesn't seem to have this issue. Because of that, I'd say there is some issue with your hosting and not Flux directly. I'm going to close this issue, but if you do discover a way we can replicate it locally, please comment back here and I will reopen the issue and investigate it. Thanks!

**Comment by mute92** [comment]
@jeffchown @joshhanley I did set up a Forge account and deployed the Livewire starter kit, but it's the exact same issue. 

https://github.com/user-attachments/assets/9339c2aa-11db-4f7b-add9-6860c2b7031e

**Comment by joshhanley** [comment]
@mute92 can you share the URL so I can have a look?

**Comment by mute92** [comment]
> [@mute92](https://github.com/mute92) can you share the URL so I can have a look?

https://bit.ly/3GoH5wP

**Comment by joshhanley** [comment]
@mute92 ah! I've seen this before. For some reason, the starter kits have `class="dark"` hard coded on the HTML element in the layout. But that causes the flash. 

https://github.com/laravel/livewire-starter-kit/blob/89830690408dfb716b16d9dccf8074056ae41747/resources/views/components/layouts/app/header.blade.php#L2

Remove that and it should stop the flash and let Flux manage it properly.

**Comment by mute92** [comment]
@joshhanley I did removed dark from both sidebar and header and it fixed the flashing when I have selected a white screen, but when I do select light its still not working.

https://github.com/user-attachments/assets/c82a7036-a68b-4713-b3ff-e88c247f831c

**Comment by joshhanley** [comment]
@mute92 sorry I don't follow what you mean. I can't tell what is happening in the video as I'm not sure when you're clicking something vs it flashing. Can you give me some more details on what you are doing and  instructions so I can follow it exactly and test it on your site (with a demo login account)? Thanks!

**Comment by mute92** [comment]
> [@mute92](https://github.com/mute92) sorry I don't follow what you mean. I can't tell what is happening in the video as I'm not sure when you're clicking something vs it flashing. Can you give me some more details on what you are doing and instructions so I can follow it exactly and test it on your site (with a demo login account)? Thanks!

@joshhanley I am clicking on dashboard and its changing the background color.

**Comment by mute92** [comment]
@joshhanley I just deployed this starter kit and connected the database.
I removed the class dark when you told me, but I have not changed anything else. 
This is the repo link https://github.com/laravel/livewire-starter-kit

**Comment by jeffchown** [comment]
@mute92 I just cloned your repo and tried on my end and all worked as expected.   I set my browser to all 3 (dark, light, same as OS) and tested it - each time, it rendered as expected with no flash when choosing `Dashboard` from the menu.

**Comment by jeffchown** [comment]
Won't have a chance to try that till tomorrow.  Did you share a link to your Forge-deployed version that we can try?

**Comment by joshhanley** [comment]
@mute92 please share your repo, not the starter kit. I want to make sure we’re all using the exact same thing. Otherwise it’s pointless as I said cloning the starter kit worked fine for me. Especially if we’re going to the effort of also deploying it.

**Comment by jeffchown** [comment]
@mute92 I thought I was cloning a repo that reproduced your issue.  I echo @joshhanley 's comment.

**Comment by mute92** [comment]
@jeffchown @joshhanley The original testing was done with the original starter kit, I just replied directly in forge and removed class"dark" with ssh.
I have cloned the repo and modified layouts, the same i did over ssh.
https://github.com/mute92/livewire-starter-kit.git

**Comment by mute92** [comment]
@joshhanley @jeffchown I just deployed one more site from the repot I sent before its exactly the same issue. When light mode is selected its working fine, when I select dark its start flashing.

**Comment by jeffchown** [comment]
@mute92 Where are you selecting light mode?  In the browser's settings?
If so, what browser are you using?

**Comment by jeffchown** [comment]
PS Please provide a link to the site you just deployed via Forge

**Comment by mute92** [comment]
@jeffchown I tried Chrome and Mozilla, and I selected in settings/appearance
Link of my website https://bit.ly/3YKv2QC

![Image](https://github.com/user-attachments/assets/e2c2eb53-75a2-4af6-a254-5a5ca89f0ba8)

**Comment by jeffchown** [comment]
@mute92 Got it.  Still can't recreate your issue.
How do you have your browser's Appearance set? (light, dark or like OS)

**Comment by mute92** [comment]
@jeffchown, is my site flashing on your side?

![Image](https://github.com/user-attachments/assets/21776c1b-53e8-4c1d-962e-51f759e2050a)

![Image](https://github.com/user-attachments/assets/c7a0e856-847e-4f92-868c-eed597546e24)

**Comment by jeffchown** [comment]
@mute92 I can't view your site, this is what I get:

![Image](https://github.com/user-attachments/assets/8001187f-85c0-42cc-85f3-2ee06d0f709c)

**Comment by mute92** [comment]
@jeffchown let me know once you open so I can remove it from the shortlink https://bit.ly/4jkxe9K

**Comment by jeffchown** [comment]
@mute92 Yes, your site does flash for me too.

When I use your site's Settings | Appearance page and choose a setting (light, dark, system), it does not store my setting between pages - which explains the flash!   When I go back to the Settings | Appearance page, none of the choices are selected.

Looks like your site is not storing the value to `$flux.appearance` for some reason.  What are your .env's cache settings set to?

**Comment by jeffchown** [comment]
Looks like your site is throwing an error re: the .js file:

![Image](https://github.com/user-attachments/assets/6ceca336-ea64-4980-91f1-101937621d58)

**Comment by mute92** [comment]
Here is my nginx, I do have flux with laravel 10 and maybe 11 and no issues on production server, but in the same production server laravel 12 does flashing. The only issue its on the production server and tested on Forge and Cloudpanel

```blade
# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/testing.domain.com/before/*;

server {
    http2 on;
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name testing.domain.com;
    server_tokens off;
    root /home/domain/testing.domain.com/public;

    # FORGE SSL (DO NOT REMOVE!)
    ssl_certificate /etc/nginx/ssl/testing.domain.com/2643538/server.crt;
    ssl_certificate_key /etc/nginx/ssl/testing.domain.com/2643538/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_dhparam /etc/nginx/dhparams.pem;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    # FORGE CONFIG (DO NOT REMOVE!)
    include forge-conf/testing.domain.com/server/*;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    location ~ ^/flux/flux(\.min)?\.(js|css)$ {
    expires off;
    try_files $uri $uri/ /index.php?$query_string;
}

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/testing.domain.com-error.log error;

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php8.4-fpm-domain.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/testing.domain.com/after/*;


```

**Comment by jeffchown** [comment]
@mute92 Did you customize the NGINX config (above) at all?

**Comment by mute92** [comment]
@jeffchown 
I only tried with adding the line from your documentation
```blade
location ~ ^/flux/flux(\.min)?\.(js|css)$ {
    expires off;
    try_files $uri $uri/ /index.php?$query_string;
}
```

**Comment by jeffchown** [comment]
@mute92 For the record, I am only a community member, a fellow Fluxer like yourself, not an official Flux staff member.

As for nginx, I read another post from someone where they removed that `location` block, restarted their server and it fixed their problem. (see: https://github.com/livewire/flux/issues/976#issuecomment-2585356131).  Have you tried that?

**Comment by mute92** [comment]
@jeffchown thank you for your effort to help, even though you are not an official Flux staff member. 
I tried with and without that line for the nginx but same issue.

@joshhanley, anything else we can try?

**Comment by mute92** [comment]
@joshhanley any solution? Were you able to test it on forge using starter kit?

**Comment by joshhanley** [comment]
@mute92 not sure sorry. @jeffchown did you get a chance to test it on Forge?

**Comment by mute92** [comment]
@joshhanley @jeffchown When i comment this line /* @custom-variant dark (&:where(.dark, .dark *)); */  in app.css and rely on the browser appearance its working without flashing.

**Comment by jeffchown** [comment]
@joshhanley I haven't had a chance to test it on Forge yet

**Comment by mute92** [comment]
@joshhanley are you able to test it?

**Comment by mute92** [comment]
@joshhanley anything on this?

**Comment by joshhanley** [comment]
@mute92 no sorry, haven't had a chance to. I don't have a spare server on Forge I can test with either

**Comment by Webotvorba** [comment]
@joshhanley I have just deployed an app with flux starter kit and I am experiencing the same issue - on Forge.

I have tried to remove the class="dark". But when I removed it and chose dark theme the flashes changed from light to dark. (My system theme is dark).

I was doing local development on herd and this issue did not appear even after removing the dark class.

I have updated also nginx config with 

```
location ~ ^/flux/flux(\.min)?\.(js|css)$ {
    expires off;
    try_files $uri $uri/ /index.php?$query_string;
}
```

but it had no effect on this
