### ISSUE TITLE
Page becomes unresponsive when navigating back to a page with wire:navigate using a popup

### ISSUE THREAD

**Issue by oskarhertzman** [livewire/flux#1923]
### Flux version

2.3.1

### Livewire version

3.6.4

### Tailwind version

4.1.12

### Browser and Operating System

Chrome on MacOS

### What is the problem?

when navigating from and back to a route that uses wire:navigate on a dropdown popup, the overlay on the html (which the popup adds) is still active and breaks page interaction.

For example:

```blade
    <flux:dropdown position="bottom" align="center">
        <flux:button variant="ghost" size="sm" icon="ellipsis-horizontal"
                     inset="top bottom"></flux:button>
        <flux:menu>
            <flux:navmenu.item href="/settings" wire:navigate>
                Settings
            </flux:navmenu.item>
        </flux:menu>
    </flux:dropdown>
```

This causes this html overlay to still be active when navigating back:

```html
<html class="sf-js-enabled" style="padding-right: calc(0px); overflow: hidden; pointer-events: none;" data-flux-scroll-unlock="{&quot;paddingRight&quot;:&quot;&quot;,&quot;overflow&quot;:&quot;&quot;,&quot;pointerEvents&quot;:&quot;&quot;}">
</html>
```

### Code snippets to replicate the problem

code example:

```blade
    <flux:dropdown position="bottom" align="center">
        <flux:button variant="ghost" size="sm" icon="ellipsis-horizontal"
                     inset="top bottom"></flux:button>
        <flux:menu>
            <flux:navmenu.item href="/settings" wire:navigate>
                Settings
            </flux:navmenu.item>
        </flux:menu>
    </flux:dropdown>
```

### How do you expect it to work?

Expecting the overlay on html to not be there.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@oskarhertzman thanks for reporting! I've just tested this and it's all working as expected for me. Any chance you could provide a small example Livewire component that demonstrates the issue, so we can investigate? Thanks!

![Image](https://github.com/user-attachments/assets/1260a45c-cb8f-4767-b8f9-e93043843218)

```blade
<?php

use Livewire\Volt\Component;

new class extends Component {
    //
}; ?>

<div>
    First page

    <flux:dropdown position="bottom" align="center">
        <flux:button>Open</flux:button>
        <flux:menu>
            <flux:navmenu.item href="/playground-3" wire:navigate>
                Second page
            </flux:navmenu.item>
        </flux:menu>
    </flux:dropdown>
</div>
```

**Comment by bbashy** [comment]
I'm seeing this too. I'll try get some working example code.

For now I've just removed wire:navigate from the links in the dropdown.

**Comment by bbashy** [comment]
It does it on a default laravel install as well.

1. `laravel new example-app`.
2. install with "Livewire", "Laravel's built-in authentication", without "Volt".
3. `composer run dev`.
4. register new user.
5. click name bottom left.
6. go back on browser.
7. can't click on anything.


https://x.bashy.im/2025-09-08-7664fbc4-6df3-4533-a245-37487b5d04ed.mp4

**Comment by oskarhertzman** [comment]
i had to do this workaround in the meantime:

app.js:

```js
/*
* TODO: Temporary fix to solve behavior with flux dropdown blocking pointer events
* this behavior stays if using browser back button
* See description here:
* https://github.com/livewire/flux/issues/1923
* */
document.addEventListener('livewire:navigated', () => {
    const html = document.documentElement;

    if (html.hasAttribute('data-flux-scroll-unlock')) {
        html.style.overflow = '';
        html.style.pointerEvents = '';
        html.removeAttribute('data-flux-scroll-unlock');
    }
});
```

**Comment by alex8013** [comment]
> 
> [https://x.basphy.im/2025-09-09-9664fbc4-6df3-4533-a245-37487b5d4ed4.mp4](https://x.bashy.im/2025-09-08-7664fbc4-6df3-4533-a245-37487b5d04ed.mp4)


The same thing happens to me.

**Comment by joshhanley** [comment]
@bbashy thanks for that, I just followed your instructions but everything worked as expected for me.

![Image](https://github.com/user-attachments/assets/f2ac93b6-a171-473a-8711-df02daa3a56a)

I'm going to close this issue as I believe it has been fixed. Make sure that Livewire, Flux, and Flux Pro are all up to date with composer and that Tailwind is up to date with NPM. Once done, run `php artisan view:clear` and then see if it works.

If anyone is still experiencing this issue after that, please push a repo to GitHub that I can pull down, and I'll have a look to see what is going on in your set up.

**Comment by alejandrotrevi** [comment]
I can confirm this is still happening in 2.5.1

https://github.com/user-attachments/assets/d9c0604b-e619-42ef-9f69-a72e7a511425

Ill try to replicate on a new project

**Comment by Webotvorba** [comment]
I can confirm that this issue persist. 

https://github.com/Webotvorba/lw-scroll 

https://share.cleanshot.com/vs85696R
