### ISSUE TITLE
data-current on menu not working

### ISSUE THREAD

**Issue by vincentcordel** [livewire/flux#284]
Documentation lacks how to properly implement the active menu.

Currently, I can't figure out how to have it recognise the current path. It stays on the root.

Routes
```
Route::name('vault.')->domain(config('app.vault_url'))->group(function () {
    Route::view('/', 'welcome')->name('homepage'); // stays there
    Route::get('/cms/pages', PagesIndex::class)->name('cms.pages.index'); // active state doesn't work when going to this page
});
```

Menu (on layout) - how to dynamically set the current on the nabber item
```
<flux:navbar class="-mb-px max-lg:hidden">
        <flux:navbar.item icon="home" href="{{ route('vault.homepage') }}" current>Home</flux:navbar.item>
        <flux:navbar.item icon="book-open" badge="12" href="{{ route('vault.cms.pages.index') }}">Pages</flux:navbar.item>
</flux:navbar>
```

**Comment by idealerror** [comment]
What version of flux are you using? Using routes on navbar items should have been fixed in this PR: https://github.com/livewire/flux/pull/26 .

Can you test if using the direct link works for the href instead of the route? `/cms/pages` instead of `route()` ?

**Comment by vincentcordel** [comment]
i tested with the hardcoded route and it works.
i’m not at my computer right now but i remember updating flux yesterday.

**Comment by idealerror** [comment]
I completely missed this... remove "current" from this line and it'll work as expected.
```
        <flux:navbar.item icon="home" href="{{ route('vault.homepage') }}" current>Home</flux:navbar.item>
```

**Comment by vincentcordel** [comment]
I already did remove the "current".
I also updated flux to 1.0.8

I still have the issue.

I'm wondering if this has to do with the domain/nested route ?

```
Route::name('vault.')->domain(config('app.vault_url'))->group(function () {
   ...
});
```
