### ISSUE TITLE
Flux Editor throws errors when used in a loop that changes order

### ISSUE THREAD

**Issue by joshhanley** [livewire/flux#806]
Currently if you use the Editor component in a loop and change the order of the loop or prepend to it, the following error gets thrown multiple times. But if you just append to the loop, it doesn't throw any errors. Interestingly even though the error gets thrown, all editors still seem to function as expected.

![Image](https://github.com/user-attachments/assets/723d9cda-b6bf-4574-b895-602be7974493)

Open the below Volt component in your browser and open the console, then either click `Append Item` which should work fine, or click `Prepend Item` which throws the error.

```blade
<?php

use Livewire\Volt\Component;

new class extends Component {

    public $items = [
        'a' => 'a',
        'b' => 'b',
        'c' => 'c',
    ];

    public function prependItem()
    {
        $this->items = ['z' => 'z'] + $this->items;
    }

    public function appendItem()
    {
        $this->items['d'] = 'd';
    }
};
?>

<flux:main container>
    <div>
        @foreach($items as $key => $value)
            <div wire:key="{{ $key }}">
                <flux:editor wire:model.live="items.{{ $key }}" :wire:key="'editor-' . $key" />
                <p>Value: {{ $value }}</p>
            </div>
        @endforeach
    </div>

    <button wire:click="prependItem">Prepend Item</button>
    <button wire:click="appendItem">Append Item</button>
</flux:main>
```

**Comment by mikecchops** [comment]
@joshhanley do you have an update on this one, or an ETA for when it might be fixed?

**Comment by joshhanley** [comment]
@mikecchops yep, I’ve fixed it! Hopefully Caleb should review it next week. 😊

**Comment by mikecchops** [comment]
@joshhanley Hi Josh - what's the update on this one? Has it been fixed on either of the latest releases?

**Comment by joshhanley** [comment]
@mikecchops Caleb has reviewed it 2 days ago, but wasn't happy with the solution, so it needs reworking. That being said, while the error is being thrown, the editor component was still functional in my testing, so it should still all work fine until we get the error cleaned up.

**Comment by mikecchops** [comment]
@joshhanley thanks for the update. Yes the editor works, but the [linked issue](https://github.com/livewire/flux/issues/809) of the content changing on sort is still an issue.

**Comment by joshhanley** [comment]
The fix has been merged and will be in the next release

**Comment by oMikeo** [comment]
Thank you @joshhanley !
